### PR TITLE
Aesthetic Cleanup and Lighting Improvements 👍 :)

### PR DESCRIPTION
**Pull request by ethanwater**
awesome code! I've made some aesthetic changes and slightly improved the lighting mechanics so it can be smoother. these changes were made simply so future onlookers can have a better understanding of the code you have written here and to allow easier navigation and overall comprehension. code is cleaner following some "aesthetic" guidelines

changes:
1. I've improved the module system, removing the pubs and allowing easier navigation and comprehension for future onlookers of the code.

2. init() now has it's own file and has been renamed to "Rubik", this is because of the functions massive size and required variables. this can be found in: init.rs

4. color constants also have their own file now in: color.rs

5. lighting of the cube is slightly smoother, i added some lazy bias using OPs a, b, and c constants. however, it can definitely be way more tuned. I just didn't feel like writing a script to do so lol. maybe someone else can further improve upon it. can be tweaked in the luminance functions. this can ofc be reverted back to the original, until a solid improvement is implemented.

6. new functions implemented to avoid code repetition, the same can be done for init (now Rubik) , but i have to work on another project so OP or someone else can tackle that.

### CODE REVIEW

**Comment by ethanwater** [comment]
also worth nothing:

in the tests i've done, it seems the overall performance has slightly improved.

**Comment by doprz** [comment]
Thank you for your PR, it looks great so I will merge it. 

Here are some thoughts:

* Could you elaborate on "lighting of the cube is slightly smoother, i added some lazy bias using OPs a, b, and c constants. however, it can definitely be way more tuned."?
* I noticed that you added this to the code and I'm not 100% sure of the purpose of dividing by a, b, and c.
```rust
    //added some simple maths so lighting is slighty smoother
    rotated_light_source.x = cos_d * cos_e * light_source.x
        + (cos_d * sin_e * sin_f - sin_d * cos_f) * light_source.y/a
        + (cos_d * sin_e * cos_f + sin_d * sin_f) * light_source.z/b;
    rotated_light_source.y = sin_d * cos_e * light_source.x
        + (sin_d * sin_e * sin_f + cos_d * cos_f) * light_source.y/a
        + (sin_d * sin_e * cos_f - cos_d * sin_f) * light_source.z/b ;
    rotated_light_source.z =
        -light_source.x/b * sin_e + light_source.y/a * cos_e * sin_f + light_source.z/c * cos_e * cos_f;
```
* I agree with your decision to move large functions into modules as I'm currently working on GPU Acceleration and making the cube interactive which makes implementing this easier. Ideally, I would let the user decide on how `rs-cube` is rendered with a CLI arg/flag, however, that is a current work in progress.
* Yes, one of the fundamental goals of `rs-cube` is performance so thank you for taking note of it.

Once again thank you for the PR and such a detailed report.

**Comment by ethanwater** [comment]
Hey! Im glad you like the changes.

Im guessing one of  my "git add ." calls didn't go through since I meant for it to be *a instead of /a. however the difference is near to none. the reasoning behind this is really just in hopes that the fluctuations between the shading parameters have less of a significant gap allowing the shading to seem "smoother". The optimal way of course is to further tweak and play with the values within the the light_source and rotated_light_source vectors. 

Besides that, I'm looking forward to seeing future progress in your code!

**Comment by doprz** [comment]
Thanks, I will refactor the code to clean things up a bit and make sure that there are no naming conflicts for GPU Acceleration.

It makes sense so I will test both the original and your lighting and decide from there. I will also add your name to the next version's release notes if you're ok with that to credit you for your contribution.

**Comment by ethanwater** [comment]
Sounds good ! And of course, I don't mind.

**Pull request merged**
